### ISSUE TITLE
Plan 0.12 release

### ISSUE THREAD

**Issue by Frando** [datrs/hypercore#114]
This is a tracking issues on what I think we should merge for a breaking 0.12 release soonish:

*breaking changes*
* [x] Move to async/await #103 
* [x] Move to generic std::error::Error #102 
* [ ] Erase generic type argument from hypercore #113 

*non-breaking changes*
* [x] New signatures for Hypercore 9 compat #112 
* [x] bugfix: put_data #110

I think it would be great to get those merged rather sooner than later, because at least the first three ones all change the public and internal API so that all other PRs oftenly have to be manually updated.

Because we don't have, I think, anyone using hypercore-rs, and because there is no one "properly" maintaining this at the moment, I propose that we let this issue sit here for a couple of days or a week and then go ahead, merge the PRs, and figure out bugs and issues in the process. 

Also very open to other suggestions :)

**Comment by bltavares** [comment]
Awesome strategy creating this issue for tracking.

I will land the PRs this Sunday and release it with RC versions then, and we can promote a 0.12 after we are able to test all of this together

**Comment by bltavares** [comment]
Trying to set network in `colmeia`, I ended up with a design where a `hyperdrive` is contained inside a `PeeredHyperdrive`, and a `hypercore` is contained on a `PeeredHypercore`.

`colmeia contains a similar protocol layer to https://github.com/Frando/hypercore-protocol-rs, producing events. The peered version of each struct contains the struct and the protocol channel in order to drive the underlying struct.

There is a set of `unimplemented!` functions related to networking on `hypercore`, but I'm thinking that we might not be able to implement it as a 1:1 mapping to JS as how Rust ownership led me to design the network methods as a wrapper to the `hypercore` struct.

@Frando I'm wondering if you will endup with a similar desing as well, and if you endup on the same desing I think it would be better to remove the network methods (eg: `have`, `unhave`) and add them to the peered layer. This would be a breaking change that could go on 0,12. What do you think?

**Comment by dumblob** [comment]
@hpk42 as discussed in https://github.com/deltachat/deltachat-core-rust/pull/3227 it seems @ttiurani works on bringing the **recent** hypercore to Rust.

So not everything is lost...

Thanks @ttiurani !

**Comment by cowlicks** [comment]
I think this issue can be closed seeing that 0.21.1 has been [released](https://discord.com/channels/709519409932140575/776019828900364289/1161911223730851870). But what is to be done about #113 ?

**Comment by ttiurani** [comment]
Closing as plans changed with v0.12 was for hypercore v10 compatibility first. #113 did not make it yet, but should be seriously re-considered for v1.0.
